-- MySQL Script generated by MySQL Workbench
-- Tue Dec 28 23:23:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FoodieSG_db
-- -----------------------------------------------------
-- The database for the FoodieSG restaurant review website

-- -----------------------------------------------------
-- Schema FoodieSG_db
--
-- The database for the FoodieSG restaurant review website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FoodieSG_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `FoodieSG_db` ;

-- -----------------------------------------------------
-- Table `FoodieSG_db`.`Account_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodieSG_db`.`Account_Info` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `gender` VARCHAR(6) NULL,
  `mobile_num` INT(8) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `profile_pic` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `mobile_num_UNIQUE` (`mobile_num` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodieSG_db`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodieSG_db`.`Restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `food_type` VARCHAR(10) NOT NULL,
  `heading` VARCHAR(5) NOT NULL,
  `overall_rating` FLOAT NOT NULL,
  `information` TEXT NOT NULL,
  `location` POINT NOT NULL,
  `photos_shop` VARCHAR(255) NULL,
  `photos_food` VARCHAR(255) NULL,
  `address` VARCHAR(150) NOT NULL,
  `opening_hours` DATETIME NOT NULL,
  `contact_num` INT(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodieSG_db`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodieSG_db`.`Reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `restaurant_id` INT NOT NULL,
  `restaurant_name` VARCHAR(64) NOT NULL,
  `review_qn_one` TEXT NOT NULL,
  `review_qn_two` TEXT NOT NULL,
  `date_posted` DATETIME NOT NULL,
  `rating` FLOAT NOT NULL,
  `picture` VARCHAR(255) NULL,
  PRIMARY KEY (`review_id`),
  INDEX `username_idx` (`username` ASC) VISIBLE,
  INDEX `restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `FoodieSG_db`.`Account_Info` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `FoodieSG_db`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodieSG_db`.`Bookmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodieSG_db`.`Bookmark` (
  `bookmark_id_` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `bookmarked_res` VARCHAR(64) NOT NULL,
  `res_id` INT NOT NULL,
  PRIMARY KEY (`bookmark_id_`),
  INDEX `user_id_idx` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `restaurant_id_UNIQUE` (`res_id` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `FoodieSG_db`.`Account_Info` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `res_id`
    FOREIGN KEY (`res_id`)
    REFERENCES `FoodieSG_db`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodieSG_db`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodieSG_db`.`Comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(15) NOT NULL,
  `comment` VARCHAR(100) NOT NULL,
  `reviewID` INT NOT NULL,
  PRIMARY KEY (`id_comments`),
  INDEX `reviewID_idx` (`reviewID` ASC) VISIBLE,
  INDEX `username_idx` (`user_name` ASC) VISIBLE,
  CONSTRAINT `reviewID`
    FOREIGN KEY (`reviewID`)
    REFERENCES `FoodieSG_db`.`Reviews` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `FoodieSG_db`.`Account_Info` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
